### ISSUE TITLE
CTRL+C does not work

### ISSUE THREAD

**Issue by cs01** [Mckinsey666/bullet#15]
It was noted in https://github.com/cs01/create-python-package/pull/9#issuecomment-468029054 by @florimondmanca that

> Bullet seems to not listen to Ctrl+C events. This means the user can't cancel while in a list prompt. 

I am working on a fix and should have a PR shortly.

**Comment by florimondmanca** [comment]
FYI, I tried Ctrl+C on macOS High Sierra, so it's possible that this issue is not specific to Linux.

**Comment by cs01** [comment]
Oh interesting. Does the pull request fix your issue on mac?

**Comment by florimondmanca** [comment]
I'll look into it soon. :eyes:

**Comment by bchao1** [comment]
Since this problem is solved by PR#20, I will close this issue.

**Comment by luckydonald** [comment]
Is this on pip yet?
