### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by luckydonald** [Mckinsey666/bullet#25]
Hey there.

It would be really useful if a default value could be set:

```py
result = YesNo(prompt="Please enter your user", default="root").launch()
```
```bash
Please enter your user [root]: _
```
When pressing enter and the input being empty (unchanged), that `default` would be the result.

This would also be great with `Bullet` and `Check`, there the `default` element(s) could be already ticked.

**Comment by SylvainDe** [comment]
I was reading the documentation then came here to report the same feature request :+1:

**Comment by Mckinsey666** [comment]
This is a great idea. I am thinking the following: for inputs (numbers, yes/no, ...),default is returned if input string is "" (empty string); for bullet and check, maybe register another key to return default value. What do you think?

**Comment by bchao1** [comment]
This feature is added! You can now define `default` in the launch() function.
