### ISSUE TITLE
Getting an image not found error?

### ISSUE THREAD

**Issue by ado120** [Mckinsey666/bullet#33]
Running the example code:
cli = Bullet(
    prompt = "\nPlease choose a fruit: ",
        choices = ["apple", "banana", "orange", "watermelon", "strawberry"], 
        indent = 0,
        align = 5, 
        margin = 2,
        shift = 0,
        bullet = "",
        pad_right = 5
)
result = cli.launch()

get's a 
`Traceback (most recent call last):
  File "test_class.py", line 6, in <module>
    from bullet import Bullet, Check, YesNo, Input
  File "/Users/alexander/Documents/GIT/virtual_envs/ucsc_final_project/lib/python3.7/site-packages/bullet/__init__.py", line 1, in <module>
    from .client import Bullet
  File "/Users/alexander/Documents/GIT/virtual_envs/ucsc_final_project/lib/python3.7/site-packages/bullet/client.py", line 7, in <module>
    import readline
ImportError: dlopen(/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/readline.cpython-37m-darwin.so
  Reason: image not found`

**Comment by rcfox** [comment]
This doesn't appear to be an issue with Bullet. From some Googling, it would seem to be an issue with the version of libreadline you have installed/the version Python is trying to use.

Try upgrading to Python 3.7.2, or if that doesn't work, this might:

`ln -s /usr/local/opt/readline/lib/libreadline.8.0.dylib /usr/local/opt/readline/lib/libreadline.7.dylib`
