### ISSUE TITLE
Calling Bullet.launch a second time causes text to overlap if the first choice wasn't taken the first time

### ISSUE THREAD

**Issue by rcfox** [Mckinsey666/bullet#6]
```
import bullet

b = bullet.Bullet('Choose one: ', choices=['dog', 'banana', 'telephone'])
b.launch()
b.launch()
```
The first time the choices are presented, choose 'telephone'

The next time, if you press the up key, 'dog' will be overwritten by 'telephone' and the prompt will be overwritten by 'banana'.

**Comment by bchao1** [comment]
Seems like I forgot to reset the cursor position. This bug is fixed, please check!
