### ISSUE TITLE
Supported Python Versions And Contribution Guidelines

### ISSUE THREAD

**Issue by mrmaxguns** [Mckinsey666/bullet#68]
# The Problem

I am highly interested in contributing to the bullet repository. However, there isn't a set of requirements to contribute. One problem is that there is no supported version of python. Python syntax, builtins, etc have changed between versions and not knowing the supported version can cause conflict. For example, say a contributor has written that only works in python version 3.7 and above.  Dependent projects might break due to this conflict.

# Proposed Solution

* Update the `setup.py` file with python version information
* At the very least, expand the [contributing](https://github.com/bchao1/bullet#contributing) section with python version info for developers. Alternatively, create a `CONTRIBUTING.md` file.

Bullet is a growing project and I hope contributors will find it easy to share their knowledge.

**Comment by bchao1** [comment]
HI, thanks for your suggestion. I've made the relevant additions to those files; hope you find them helpful.
